const idioma: any = {
  "is required": "es requerido",
  "must be the same": "debe ser igual",
  characters: "caracteres",
  min: "min",
  max: "max",
  "is not a valid value": "no es un valor válido",
  "is not a valid email": "no es un email válido",
  "is not a number": "no es un número",
  "is not a valid text": "no es un texto válido",
  "must be greater than": "debe ser mayor que",
  "must be less than ": "debe ser menor que",
  "must be between ": "debe star entre",
  and: "y",
  list: "listado de {0}",
  add: "adicionar",
  edit: "editar",
  delete: "borrar",
  update: "actualizar",
  view: "ver",
  save: "grabar",
  cancel: "cancelar",
  search: "buscar",
  all: "todos",
  active: "activo",
  inactive: "inactivo",
  user: "usuario",
  admin: "administrador",
  adm: "adminitrador",
  team: "equipo",
  owner: "propietario",
  actions: "acciones",
  "empty data": "no hay datos",
  "are you sure you want to delete the record?":
    "seguro de eliminar el registro?",
  settings: "configuración",
  "sign out": "cerrar sesión",
  wellcome: "bienvenido",
};
export default idioma;
